name: Helle world workflow

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: print hello world
        run: echo "Hello worl" && sleep 30 
      - name: print hello hello newera solution
        run: echo "Hello newera solution"     
        
